export const ADD_LAYOUT_PANEL = 'ADD_LAYOUT_PANEL';
export const SET_GUIDE_CONFIG = 'SET_GUIDE_CONFIG';
export const ADD_GUIDE_CONTAINER = 'ADD_GUIDE_CONTAINER';
export const DELETE_GUIDE_CONTAINER = 'DELETE_GUIDE_CONTAINER';
export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_LAYOUT_NAME = 'SET_LAYOUT_NAME';
export const SET_LAYOUT_WIDTH = 'SET_LAYOUT_WIDTH';
export const SET_LAYOUT_HEIGHT = 'SET_LAYOUT_HEIGHT';
export const SET_LAYOUT_BACKGROUND = 'SET_LAYOUT_BACKGROUND';
export const DELETE_LAYOUT = 'DELETE_LAYOUT';
export const COL_CUT = 'COL_CUT';
export const ROW_CUT = 'ROW_CUT';
export const DELETE_HORIZONTAL = 'DELETE_HORIZONTAL';
export const DELETE_VERTICAL = 'DELETE_VERTICAL';
export const SET_LAYOUT_SMALL_BACK = 'SET_LAYOUT_SMALL_BACK';
export const SET_COL_WIDTH = 'SET_COL_WIDTH';
export const SET_ROW_HEIGHT = 'SET_ROW_HEIGHT';

export const ADD_NEW_RECT = 'ADD_NEW_RECT';
export const SET_ACTIVATE_EV = 'SET_ACTIVATE_EV';
export const CHANGE_RECT = 'CHANGE_RECT';
export const CHANGE_CONFIG = 'CHANGE_CONFIG';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';

export const SET_COMRESOURCE = 'SET_COMRESOURCE';
export const SET_COPY_RESOURCE = 'SET_COPY_RESOURCE';
export const GET_COPY_RESOURCE = 'GET_COPY_RESOURCE';

export default {
    ADD_LAYOUT_PANEL,
    SET_GUIDE_CONFIG,
    ADD_GUIDE_CONTAINER,
    DELETE_GUIDE_CONTAINER,
    SET_LAYOUT,
    SET_LAYOUT_NAME,
    SET_LAYOUT_WIDTH,
    SET_LAYOUT_HEIGHT,
    SET_LAYOUT_BACKGROUND,
    DELETE_LAYOUT,
    COL_CUT,
    ROW_CUT,
    DELETE_HORIZONTAL,
    DELETE_VERTICAL,
    SET_LAYOUT_SMALL_BACK,
    SET_COL_WIDTH,
    SET_ROW_HEIGHT,
    ADD_NEW_RECT,
    SET_ACTIVATE_EV,
    CHANGE_RECT,
    CHANGE_CONFIG,
    DELETE_ELEMENT,
    SET_COMRESOURCE,
    SET_COPY_RESOURCE,
    GET_COPY_RESOURCE
}